name: 'Build Debian Packages'
description: 'Build all .deb packages (store + container apps)'

runs:
  using: 'composite'
  steps:
    - name: Build Docker image
      shell: bash
      run: |
        docker build -f docker/Dockerfile.build -t marine-builder .

    - name: Build packages in Docker
      shell: bash
      run: |
        docker run --rm \
          -v "$PWD:/workspace" \
          -w /workspace \
          marine-builder \
          ./tools/build-all.sh
