name: 'Build Debian Packages'
description: 'Build all .deb packages (store + container apps)'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get container-packaging-tools version
      id: tools-version
      shell: bash
      run: |
        VERSION=$(curl -s https://api.github.com/repos/hatlabs/container-packaging-tools/releases/latest | jq -r '.tag_name')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Using container-packaging-tools: $VERSION"

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.build
        tags: marine-builder
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          CONTAINER_TOOLS_VERSION=${{ steps.tools-version.outputs.version }}

    - name: Build packages in Docker
      shell: bash
      run: |
        docker run --rm \
          -u $(id -u):$(id -g) \
          -v "$PWD:/workspace" \
          -w /workspace \
          marine-builder \
          ./tools/build-all.sh
