apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: marine
    jsonData:
      httpMode: POST
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Token $__env{INFLUXDB_TOKEN}
    isDefault: true
    editable: true
